# Generated by Django 5.0.7 on 2024-08-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='guest_user', max_length=255),
            preserve_default=False,
        ),
    ]
