# Generated by Django 5.0.7 on 2024-08-19 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_joined_alter_user_is_staff_and_more'),
        ('customer', '0004_user_username'),
    ]

    operations = [
    ]
