# Generated by Django 5.0.7 on 2024-08-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('reviews', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
