# Generated by Django 5.0.7 on 2024-08-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image_alter_product_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
